import type { Metadata } from "next";
import { Outfit } from "next/font/google";

import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/session-provider";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import LoadingProviders from "@/components/LoaderProvider";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Formatify",
  description: "Generated by great developers",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={outfit.className}>
        <SessionProvider session={session}>
          <Providers>
            <LoadingProviders>
              {children}
            </LoadingProviders>
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
